#! /bin/sh

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

clone_repo_commit() {
    if test -d $2/.git; then
        git -C $2 reset --hard
        git -C $2 clean -fd
        if ! git -C $2 checkout $3; then
            rm -rf $2
        fi
    else
        if test -d $2; then
            echo "error: '$2' is not a Git repository"
            exit 1
        fi
    fi
    if ! test -d $2; then
        git clone $1 $2
        git -C $2 checkout $3
    fi
}

download_by_hash() {
    DOWNLOAD_COMMAND="curl -Lo"
    if ! command -v $DOWNLOAD_COMMAND >/dev/null 2>&1; then
        DOWNLOAD_COMMAND="wget -O"
        if ! command -v $DOWNLOAD_COMMAND >/dev/null 2>&1; then
            echo "error: Neither curl nor wget found"
            exit 1
        fi
    fi
    SHA256_COMMAND="sha256sum"
    if ! command -v $SHA256_COMMAND >/dev/null 2>&1; then
        SHA256_COMMAND="sha256"
        if ! command -v $SHA256_COMMAND >/dev/null 2>&1; then
            echo "error: Cannot find sha256(sum) command"
            exit 1
        fi
    fi
    if ! test -f $2 || ! $SHA256_COMMAND $2 | grep $3 >/dev/null 2>&1; then
        rm -f $2
        mkdir -p $2 && rm -rf $2
        $DOWNLOAD_COMMAND $2 $1
        if ! $SHA256_COMMAND $2 | grep $3 >/dev/null 2>&1; then
            echo "error: Cannot download file '$2' by hash"
            exit 1
        fi
    fi
}

if ! test -f version; then
    clone_repo_commit \
        https://github.com/osdev0/freestanding-headers.git \
        freestanding-headers \
        dd3abd2d7147efc4170dff478d3b7730bed14147

    download_by_hash \
        https://github.com/osdev0/cc-runtime/raw/dcdf5d82973e77edee597a047a3ef66300903de9/cc-runtime.c \
        src/cc-runtime.c \
        199907f5303ab15a963377fabcc1f2ee736e4ed18d54c59aab08345aa5485e8a

    download_by_hash \
        https://github.com/limine-bootloader/limine/raw/cf501adb63e2d5d7a68911887df6651bde4348aa/limine.h \
        src/limine.h \
        de2789b4dfceda28a11e98603a302d8d7ebbc2c1f87fa90ea475e37a991b4209
fi
